CREATE TABLE MEMBER (
  MEMBER_ID         BIGINT(20)   NOT NULL AUTO_INCREMENT,
  EMAIL             VARCHAR(100) NOT NULL,
  PASSWORD          VARCHAR(100) NOT NULL
  COMMENT 'ハッシュ化したものを保存',
  NAME              VARCHAR(100) NOT NULL,
  REGISTER_DATETIME DATETIME     NOT NULL,
  REGISTER_USER     VARCHAR(100) NOT NULL,
  UPDATE_DATETIME   DATETIME     NOT NULL,
  UPDATE_USER       VARCHAR(100) NOT NULL,
  VERSION_NO        BIGINT(20)   NOT NULL,
  PRIMARY KEY (MEMBER_ID),
  UNIQUE (EMAIL, NAME)
)
  ENGINE = INNODB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE TWEET (
  TWEET_ID          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  MEMBER_ID         BIGINT(20)   NOT NULL,
  TWEET             VARCHAR(140) NOT NULL,
  TWEET_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  REGISTER_DATETIME DATETIME     NOT NULL,
  REGISTER_USER     VARCHAR(100) NOT NULL,
  UPDATE_DATETIME   DATETIME     NOT NULL,
  UPDATE_USER       VARCHAR(100) NOT NULL,
  VERSION_NO        BIGINT(20)   NOT NULL,
  PRIMARY KEY (TWEET_ID),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE FOLLOW (
  FOLLOWER_ID       BIGINT(20)   NOT NULL,
  FOLLOWED_ID       BIGINT(20)   NOT NULL,
  REGISTER_DATETIME DATETIME     NOT NULL,
  REGISTER_USER     VARCHAR(100) NOT NULL,
  UPDATE_DATETIME   DATETIME     NOT NULL,
  UPDATE_USER       VARCHAR(100) NOT NULL,
  VERSION_NO        BIGINT(20)   NOT NULL,
  UNIQUE (FOLLOWER_ID, FOLLOWED_ID),
  FOREIGN KEY (FOLLOWED_ID) REFERENCES MEMBER (MEMBER_ID),
  FOREIGN KEY (FOLLOWER_ID) REFERENCES MEMBER (MEMBER_ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = utf8mb4;

CREATE TABLE TWEET_EVALUATE (
  TWEET_ID          BIGINT(20)   NOT NULL
  COMMENT '評価されるコメントのID',
  EVALUATE_STATUS   VARCHAR(5)       NOT NULL
  COMMENT '評価の状態 GOOD:いいね､BAD:どうでもいいね',
  MEMBER_ID         BIGINT(20)   NOT NULL
  COMMENT '評価する人のID',
  REGISTER_DATETIME DATETIME     NOT NULL,
  REGISTER_USER     VARCHAR(100) NOT NULL,
  UPDATE_DATETIME   DATETIME     NOT NULL,
  UPDATE_USER       VARCHAR(100) NOT NULL,
  VERSION_NO        BIGINT(20)   NOT NULL,
  UNIQUE (TWEET_ID, MEMBER_ID),
  FOREIGN KEY (TWEET_ID) REFERENCES TWEET (TWEET_ID),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = utf8mb4;
